# Generated by Django 3.0.4 on 2020-03-28 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200328_1117'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storecustomer',
            unique_together={('customer', 'store')},
        ),
    ]
