# Generated by Django 3.0.4 on 2020-03-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200325_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='remainMoney',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
