# Generated by Django 3.0.4 on 2020-03-27 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200327_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='remainMoney',
            new_name='credit',
        ),
    ]
