# Generated by Django 3.0.4 on 2020-03-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_auto_20200325_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='caption',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='content',
            field=models.FileField(default=' ', upload_to='files'),
            preserve_default=False,
        ),
    ]
