# Generated by Django 3.0.4 on 2020-03-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_auto_20200328_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='fee',
            field=models.SmallIntegerField(default=100),
            preserve_default=False,
        ),
    ]
