# Generated by Django 3.0.4 on 2020-03-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('price', models.SmallIntegerField()),
            ],
        ),
    ]
