# Generated by Django 3.0.4 on 2020-03-28 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('store', '0002_store_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='user.Admin'),
        ),
    ]
